// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools 2015 v1.7.158
// </auto-generated>
// ------------------------------------------------------------------------------
namespace PackmanVsix
{
    static class Vsix
    {
        public const string Id = "ce753d0f-f511-4b2b-93de-5cc50145dca6";
        public const string Name = "Client-Side Library Installer";
        public const string Description = "A simple solution to installing JavaScript and CSS libraries into any project. It uses well established global content delivery networks that hosts thousands of the most popular libraries.";
        public const string Language = "en-US";
        public const string Version = "1.2";
        public const string Author = "Mads Kristensen";
        public const string Tags = "jsdelivr, cdn, packages, library, javascript, css";
    }
}
